name: 'Publish Anaconda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Maxime Borry, Brian Fulton-Howard and Jonathan Shimwell'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
  channels:
    description: 'Additional anaconda channels'
    default: '{-c conda-forge}'
  publish:
    description: 'Whether to publish to anaconda'
    default: 'false'
  convert_win:
    description: 'Whether to convert linux build for windows'
    default: 'false'
  convert_osx:
    description: 'Whether to convert linux build for osx'
    default: 'false'
  test_all:
    description: 'Whether to build and test all recipe variants'
    default: 'false'
  test_pyver:
    description: 'Default version of Python to test the package with'
    default: '3.7'
  test_npver:
    description: 'Default version of NumPy to test the package with'
    default: '1.18'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
