name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Maxime Borry'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
  channels:
    description: 'Additional anaconda channels'
    default: '{conda-forge}'
  publish:
    description: 'Whether to publish to anaconda'
    default: 'false'
  convert_win:
    description: 'Whether to convert linux build for windows'
    default: 'true'
  convert_osx:
    description: 'Whether to convert linux build for osx'
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
